# Generated by Django 5.2.7 on 2025-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='author',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='author',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
        migrations.AddField(
            model_name='author',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
