# Generated by Django 5.2.7 on 2025-11-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='articles_image_path'),
        ),
    ]
